@echo off
setlocal EnableDelayedExpansion
cd /d "%~dp0"

rem ============================================================
rem  Project Setup  [self-unpacking]
rem  Generated by Venv Batch Template Generator (Leon Priest / 7h3v01d) v3.4.0
rem  Generated on: 2026-07-20 00:45
rem
rem  Ship ONLY this file in your repo.  On first run it:
rem    1. Checks Python
rem    2. Creates / verifies the virtual environment
rem    3. Installs dependencies
rem    4. Writes companion scripts beside this file:
rem       run.bat  pip.bat  shell.bat  sync.bat  doctor.bat  test.bat
rem
rem  Companion scripts are NOT overwritten if they already exist.
rem  Add them to .gitignore to keep your repo tidy.
rem ============================================================

set "PROJECT_NAME=adp_pro"
set "VENV_DIR=.venv"

title "%PROJECT_NAME% - SETUP"

echo ============================================================
echo  Setup: %PROJECT_NAME%
echo ============================================================
echo.

rem ── 1. Environment check + venv bootstrap ───────────────────
where python >nul 2>&1
if errorlevel 1 (
    echo [ERROR] Python is not installed or not on PATH.
    echo.
    echo Install Python from https://www.python.org/downloads/
    echo Make sure to check "Add Python to PATH" during installation.
    echo.
    pause
    exit /b 1
)

if exist "%VENV_DIR%\Scripts\python.exe" (
    echo [INFO] Virtual environment already exists at "%VENV_DIR%\"
    echo        Skipping creation.
    echo.
) else (
    echo [1/3] Creating virtual environment...
    echo ============================================================
    python -m venv "%VENV_DIR%"
    if errorlevel 1 ( echo [ERROR] venv creation failed. & pause & exit /b 1 )
    echo.

    echo [2/3] Upgrading pip...
    echo ============================================================
    "%VENV_DIR%\Scripts\python.exe" -m pip install --upgrade pip
    echo.

    if exist "requirements.txt" (
        echo [3/3] Installing dependencies from requirements.txt...
        echo ============================================================
        "%VENV_DIR%\Scripts\python.exe" -m pip install -r requirements.txt
        echo.
    ) else (
        echo [3/3] SKIPPED: No requirements.txt found.
        echo        Run sync.bat after adding dependencies.
        echo.
    )
)

rem ── 2. Write companion scripts ───────────────────────────────
rem -- Editable install of the package itself --------------------
rem  With the src/ layout, "adp" is only importable once the package
rem  is installed. An editable (-e) install links src/ onto the path so
rem  run.bat (python -m adp.main), test.bat (pytest) and a bare "pytest"
rem  all work from anywhere with no PYTHONPATH juggling. Safe to re-run.
rem
rem  The [dev] extra pulls the test-only tooling (pytest-qt for the qtbot/
rem  qapp fixtures, pytest-timeout for @pytest.mark.timeout, pytest-mock).
rem  Without it, every GUI/API/torrent test errors at setup with
rem  "fixture 'qtbot' not found" and pytest warns "Unknown config option:
rem  qt_api" -- the whole test suite can't run.
echo ============================================================
echo  Installing project + dev tools (editable) ...
echo ============================================================
"%VENV_DIR%\Scripts\python.exe" -m pip install -e ".[dev]"
if errorlevel 1 ( echo [ERROR] Editable install failed. & pause & exit /b 1 )
echo.

echo ============================================================
echo  Writing companion scripts...
echo ============================================================
echo.

rem ── run.bat ─────────────────────────────────────────────────
set "OUTFILE=run.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_run_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbCBFbmFibGVEZWxheWVkRXhwYW5zaW9uDQpjZCAvZCAiJX5kcDAi
        echo DQoNCnJlbSA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT0NCnJlbSAgUHJvamVjdCBSdW5uZXINCnJlbSAgR2VuZXJhdGVkIGJ5IFZlbnYg
        echo QmF0Y2ggVGVtcGxhdGUgR2VuZXJhdG9yIChMZW9uIFByaWVzdCAvIDdoM3YwMWQpIHYzLjQuMA0K
        echo cmVtICBHZW5lcmF0ZWQgb246IDIwMjYtMDctMjAgMDA6NDUNCnJlbQ0KcmVtICBFTlRSWV9NT0RF
        echo Og0KcmVtICAgIGZpbGUgICAtPiBweXRob24gYXBwLnB5DQpyZW0gICAgbW9kdWxlIC0+IHB5dGhv
        echo biAtbSBwYWNrYWdlLm1vZHVsZQ0KcmVtICAgIHJ1bm5lciAtPiBweXRob24gLW0gcnVubmVyX21v
        echo ZHVsZSBbYXJncy4uLl0NCnJlbSA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT0NCg0Kc2V0ICJQUk9KRUNUX05BTUU9YWRwX3BybyINCnNl
        echo dCAiVkVOVl9ESVI9LnZlbnYiDQpzZXQgIkVOVFJZX01PREU9bW9kdWxlIg0Kc2V0ICJBUFBfRU5U
        echo Ulk9YWRwLm1haW4iDQpzZXQgIlJVTk5FUl9BUkdTPSINCg0Kc2V0ICJQWT0lQ0QlXCVWRU5WX0RJ
        echo UiVcU2NyaXB0c1xweXRob24uZXhlIg0KDQppZiBub3QgZXhpc3QgIiVQWSUiICgNCiAgICBlY2hv
        echo IFtFUlJPUl0gTG9jYWwgdmVudiBub3QgZm91bmQ6ICIlUFklIg0KICAgIGVjaG8uDQogICAgZWNo
        echo byBGaXggd2l0aDoNCiAgICBlY2hvICAgcHl0aG9uIC1tIHZlbnYgIiVWRU5WX0RJUiUiDQogICAg
        echo ZWNobyAgICIlVkVOVl9ESVIlXFNjcmlwdHNccHl0aG9uLmV4ZSIgLW0gcGlwIGluc3RhbGwgLS11
        echo cGdyYWRlIHBpcA0KICAgIGVjaG8gICAiJVZFTlZfRElSJVxTY3JpcHRzXHB5dGhvbi5leGUiIC1t
        echo IHBpcCBpbnN0YWxsIC1yIHJlcXVpcmVtZW50cy50eHQNCiAgICBlY2hvLg0KICAgIHBhdXNlDQog
        echo ICAgZXhpdCAvYiAxDQopDQoNCmlmIC9JICIlRU5UUllfTU9ERSUiPT0iZmlsZSIgaWYgbm90IGV4
        echo aXN0ICIlQVBQX0VOVFJZJSIgKA0KICAgIGVjaG8gW0VSUk9SXSBFbnRyeSBmaWxlIG5vdCBmb3Vu
        echo ZDogIiVBUFBfRU5UUlklIg0KICAgIGVjaG8gRWRpdCBydW4uYmF0IG9yIHJ1biB3aXRoIHRoZSBj
        echo b3JyZWN0IGVudHJ5IGZpbGUuDQogICAgcGF1c2UNCiAgICBleGl0IC9iIDENCikNCg0KdGl0bGUg
        echo IiVQUk9KRUNUX05BTUUlIC0gUlVOIg0KZWNobyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCmVjaG8gIFJ1bm5pbmcgOiAlUFJPSkVD
        echo VF9OQU1FJQ0KZWNobyAgUHJvamVjdCA6ICVDRCUNCmVjaG8gIFB5dGhvbiAgOiAlUFklDQplY2hv
        echo ICBNb2RlICAgIDogJUVOVFJZX01PREUlDQplY2hvICBFbnRyeSAgIDogJUFQUF9FTlRSWSUNCmlm
        echo IC9JICIlRU5UUllfTU9ERSUiPT0icnVubmVyIiBlY2hvICBBcmdzICAgIDogJVJVTk5FUl9BUkdT
        echo JQ0KZWNobyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT0NCmVjaG8uDQoNCnNldCAiRVhJVENPREU9MCINCg0KaWYgL0kgIiVFTlRSWV9N
        echo T0RFJSI9PSJtb2R1bGUiICgNCiAgICAiJVBZJSIgLW0gJUFQUF9FTlRSWSUgJSoNCikgZWxzZSBp
        echo ZiAvSSAiJUVOVFJZX01PREUlIj09InJ1bm5lciIgKA0KICAgIGlmIGRlZmluZWQgUlVOTkVSX0FS
        echo R1MgKA0KICAgICAgICAiJVBZJSIgLW0gJUFQUF9FTlRSWSUgIVJVTk5FUl9BUkdTISAlKg0KICAg
        echo ICkgZWxzZSAoDQogICAgICAgICIlUFklIiAtbSAlQVBQX0VOVFJZJSAlKg0KICAgICkNCikgZWxz
        echo ZSAoDQogICAgIiVQWSUiICIlQVBQX0VOVFJZJSIgJSoNCikNCg0Kc2V0ICJFWElUQ09ERT0hRVJS
        echo T1JMRVZFTCEiDQoNCmVjaG8uDQplY2hvID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PQ0KZWNobyAgUHJvY2VzcyBleGl0ZWQgd2l0aCBj
        echo b2RlOiAhRVhJVENPREUhDQplY2hvID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PQ0KcGF1c2UNCmV4aXQgL2IgIUVYSVRDT0RFIQ0K
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── pip.bat ─────────────────────────────────────────────────
set "OUTFILE=pip.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_pip_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbA0KY2QgL2QgIiV+ZHAwIg0KDQpyZW0gPT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpyZW0gIFByb2pl
        echo Y3QtbG9jYWwgcGlwIHdyYXBwZXINCnJlbSAgR2VuZXJhdGVkIGJ5IFZlbnYgQmF0Y2ggVGVtcGxh
        echo dGUgR2VuZXJhdG9yIChMZW9uIFByaWVzdCAvIDdoM3YwMWQpIHYzLjQuMA0KcmVtICBHZW5lcmF0
        echo ZWQgb246IDIwMjYtMDctMjAgMDA6NDUNCnJlbQ0KcmVtICBVc2FnZToNCnJlbSAgICBwaXAuYmF0
        echo IGluc3RhbGwgcmVxdWVzdHMNCnJlbSAgICBwaXAuYmF0IGluc3RhbGwgLXIgcmVxdWlyZW1lbnRz
        echo LnR4dA0KcmVtICAgIHBpcC5iYXQgZnJlZXplID4gcmVxdWlyZW1lbnRzLnR4dA0KcmVtICAgIHBp
        echo cC5iYXQgbGlzdA0KcmVtICAgIHBpcC5iYXQgdW5pbnN0YWxsIHJlcXVlc3RzDQpyZW0gPT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQoN
        echo CnNldCAiVkVOVl9ESVI9LnZlbnYiDQpzZXQgIlBZPSVDRCVcJVZFTlZfRElSJVxTY3JpcHRzXHB5
        echo dGhvbi5leGUiDQoNCmlmIG5vdCBleGlzdCAiJVBZJSIgKA0KICAgIGVjaG8gW0VSUk9SXSBMb2Nh
        echo bCB2ZW52IHdhcyBub3QgZm91bmQ6DQogICAgZWNobyAgICAgICAgICIlUFklIg0KICAgIGVjaG8u
        echo DQogICAgZWNobyBDcmVhdGUgaXQgd2l0aDoNCiAgICBlY2hvICAgICAgICAgcHl0aG9uIC1tIHZl
        echo bnYgIiVWRU5WX0RJUiUiDQogICAgZWNoby4NCiAgICBwYXVzZQ0KICAgIGV4aXQgL2IgMQ0KKQ0K
        echo DQoiJVBZJSIgLW0gcGlwICUqDQpleGl0IC9iICVFUlJPUkxFVkVMJQ0K
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── shell.bat ─────────────────────────────────────────────────
set "OUTFILE=shell.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_shell_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpjZCAvZCAiJX5kcDAiDQoNCnJlbSA9PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCnJlbSAgUHJvamVjdCB2ZW52IHNo
        echo ZWxsDQpyZW0gIEdlbmVyYXRlZCBieSBWZW52IEJhdGNoIFRlbXBsYXRlIEdlbmVyYXRvciAoTGVv
        echo biBQcmllc3QgLyA3aDN2MDFkKSB2My40LjANCnJlbSAgR2VuZXJhdGVkIG9uOiAyMDI2LTA3LTIw
        echo IDAwOjQ1DQpyZW0NCnJlbSAgT3BlbnMgYW4gYWN0aXZhdGVkIENNRCBzZXNzaW9uIGZvciB0aGlz
        echo IHByb2plY3QuDQpyZW0gIFVzZSBvbmx5IHdoZW4geW91IG5lZWQgYW4gaW50ZXJhY3RpdmUgdmVu
        echo diBzZXNzaW9uLg0KcmVtICBFeGl0IHdpdGg6IGV4aXQNCnJlbSA9PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCg0Kc2V0ICJQUk9KRUNU
        echo X05BTUU9YWRwX3BybyINCnNldCAiVkVOVl9ESVI9LnZlbnYiDQpzZXQgIkFDVElWQVRFPSVDRCVc
        echo JVZFTlZfRElSJVxTY3JpcHRzXGFjdGl2YXRlLmJhdCINCg0KaWYgbm90IGV4aXN0ICIlQUNUSVZB
        echo VEUlIiAoDQogICAgZWNobyBbRVJST1JdIExvY2FsIHZlbnYgd2FzIG5vdCBmb3VuZDoNCiAgICBl
        echo Y2hvICAgICAgICAgIiVBQ1RJVkFURSUiDQogICAgZWNoby4NCiAgICBlY2hvIENyZWF0ZSBpdCB3
        echo aXRoOg0KICAgIGVjaG8gICAgICAgICBweXRob24gLW0gdmVudiAiJVZFTlZfRElSJSINCiAgICBl
        echo Y2hvLg0KICAgIHBhdXNlDQogICAgZXhpdCAvYiAxDQopDQoNCnRpdGxlICIlUFJPSkVDVF9OQU1F
        echo JSAtIFZFTlYgU0hFTEwiDQpjYWxsICIlQUNUSVZBVEUlIg0KDQplY2hvID09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQ0KZWNobyAgUHJv
        echo amVjdCBzaGVsbCBhY3RpdmF0ZWQNCmVjaG8gIFByb2plY3Q6ICIlQ0QlIg0KZWNobyAgUHl0aG9u
        echo IDoNCndoZXJlIHB5dGhvbg0KZWNobyAgVHlwZSAiZXhpdCIgdG8gbGVhdmUgdGhpcyBzaGVsbC4N
        echo CmVjaG8gPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09DQplY2hvLg0KY21kIC9rDQo=
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── sync.bat ─────────────────────────────────────────────────
set "OUTFILE=sync.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_sync_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbA0KY2QgL2QgIiV+ZHAwIg0KDQpyZW0gPT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpyZW0gIERlcGVu
        echo ZGVuY3kgU3luYyAocGlwKQ0KcmVtICBHZW5lcmF0ZWQgYnkgVmVudiBCYXRjaCBUZW1wbGF0ZSBH
        echo ZW5lcmF0b3IgKExlb24gUHJpZXN0IC8gN2gzdjAxZCkgdjMuNC4wDQpyZW0gIEdlbmVyYXRlZCBv
        echo bjogMjAyNi0wNy0yMCAwMDo0NQ0KcmVtID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PQ0KDQpzZXQgIlBST0pFQ1RfTkFNRT1hZHBfcHJv
        echo Ig0Kc2V0ICJWRU5WX0RJUj0udmVudiINCnNldCAiUFk9JUNEJVwlVkVOVl9ESVIlXFNjcmlwdHNc
        echo cHl0aG9uLmV4ZSINCg0KaWYgbm90IGV4aXN0ICIlUFklIiAoDQogICAgZWNobyBbRVJST1JdIExv
        echo Y2FsIHZlbnYgbm90IGZvdW5kOiAiJVBZJSINCiAgICBlY2hvLg0KICAgIGVjaG8gQ3JlYXRlIGl0
        echo IHdpdGg6DQogICAgZWNobyAgIHB5dGhvbiAtbSB2ZW52ICIlVkVOVl9ESVIlIg0KICAgIHBhdXNl
        echo DQogICAgZXhpdCAvYiAxDQopDQoNCnRpdGxlICIlUFJPSkVDVF9OQU1FJSAtIFNZTkMiDQoNCmVj
        echo aG8gPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09DQplY2hvICBTeW5jaW5nOiAlUFJPSkVDVF9OQU1FJQ0KZWNobyAgUHl0aG9uIDogJVBZ
        echo JQ0KZWNobyA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT0NCmVjaG8uDQoNCmVjaG8gWzEvM10gVXBncmFkaW5nIHBpcC4uLg0KZWNobyA9
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT0NCiIlUFklIiAtbSBwaXAgaW5zdGFsbCAtLXVwZ3JhZGUgcGlwDQplY2hvLg0KDQppZiBleGlz
        echo dCAicmVxdWlyZW1lbnRzLnR4dCIgKA0KICAgIGVjaG8gWzIvM10gSW5zdGFsbGluZyBmcm9tIHJl
        echo cXVpcmVtZW50cy50eHQuLi4NCiAgICBlY2hvID09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQ0KICAgICIlUFklIiAtbSBwaXAgaW5zdGFs
        echo bCAtciByZXF1aXJlbWVudHMudHh0DQogICAgZWNoby4NCikgZWxzZSAoDQogICAgZWNobyBbMi8z
        echo XSBTS0lQUEVEOiBObyByZXF1aXJlbWVudHMudHh0IGZvdW5kLg0KICAgIGVjaG8gICAgICAgQ3Jl
        echo YXRlIG9uZSB3aXRoOiBwaXAuYmF0IGZyZWV6ZSBePiByZXF1aXJlbWVudHMudHh0DQogICAgZWNo
        echo by4NCikNCg0KZWNobyBbMy8zXSBEZXBlbmRlbmN5IGhlYWx0aCBjaGVjay4uLg0KZWNobyA9PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0N
        echo CiIlUFklIiAtbSBwaXAgY2hlY2sNCmVjaG8uDQoNCmVjaG8gPT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQplY2hvICBTWU5DIENPTVBM
        echo RVRFDQplY2hvID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PQ0KcGF1c2UNCmV4aXQgL2IgMA0K
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── doctor.bat ─────────────────────────────────────────────────
set "OUTFILE=doctor.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_doctor_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbA0KY2QgL2QgIiV+ZHAwIg0KDQpyZW0gPT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpyZW0gIFByb2pl
        echo Y3QgRG9jdG9yDQpyZW0gIEdlbmVyYXRlZCBieSBWZW52IEJhdGNoIFRlbXBsYXRlIEdlbmVyYXRv
        echo ciAoTGVvbiBQcmllc3QgLyA3aDN2MDFkKSB2My40LjANCnJlbSAgR2VuZXJhdGVkIG9uOiAyMDI2
        echo LTA3LTIwIDAwOjQ1DQpyZW0gPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09DQoNCnNldCAiUFJPSkVDVF9OQU1FPWFkcF9wcm8iDQpzZXQg
        echo IlZFTlZfRElSPS52ZW52Ig0Kc2V0ICJFTlRSWV9NT0RFPW1vZHVsZSINCnNldCAiQVBQX0VOVFJZ
        echo PWFkcC5tYWluIg0Kc2V0ICJSVU5ORVJfQVJHUz0iDQpzZXQgIlBZPSVDRCVcJVZFTlZfRElSJVxT
        echo Y3JpcHRzXHB5dGhvbi5leGUiDQoNCmVjaG8gPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQplY2hvICBQUk9KRUNUIERPQ1RPUjogJVBS
        echo T0pFQ1RfTkFNRSUNCmVjaG8gPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09DQplY2hvICBQcm9qZWN0IDogJUNEJQ0KZWNobyAgTW9kZSAg
        echo ICA6ICVFTlRSWV9NT0RFJQ0KZWNobyAgRW50cnkgICA6ICVBUFBfRU5UUlklDQppZiAvSSAiJUVO
        echo VFJZX01PREUlIj09InJ1bm5lciIgZWNobyAgQXJncyAgICA6ICVSVU5ORVJfQVJHUyUNCmVjaG8u
        echo DQoNCmlmIG5vdCBleGlzdCAiJVBZJSIgKA0KICAgIGVjaG8gW0ZBSUxdIHZlbnYgbm90IGZvdW5k
        echo IGF0OiAiJVBZJSINCiAgICBlY2hvLg0KICAgIGVjaG8gQ3JlYXRlIGl0IHdpdGg6DQogICAgZWNo
        echo byAgIHB5dGhvbiAtbSB2ZW52ICIlVkVOVl9ESVIlIg0KICAgIHBhdXNlDQogICAgZXhpdCAvYiAx
        echo DQopDQoNCmVjaG8gW09LXSB2ZW52IGZvdW5kOiAiJVBZJSINCmVjaG8uDQoNCmVjaG8gLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tDQpl
        echo Y2hvICBQeXRob24gRW52aXJvbm1lbnQNCmVjaG8gLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tDQoiJVBZJSIgLWMgImltcG9ydCBzeXM7
        echo IHByaW50KCdFeGVjdXRhYmxlIDonLCBzeXMuZXhlY3V0YWJsZSk7IHByaW50KCdWZXJzaW9uICAg
        echo IDonLCBzeXMudmVyc2lvbi5zcGxpdCgpWzBdKTsgcHJpbnQoJ1ByZWZpeCAgICAgOicsIHN5cy5w
        echo cmVmaXgpIg0KZWNoby4NCg0KZWNobyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0NCmVjaG8gIHBpcCB2ZXJzaW9uDQplY2hvIC0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQ0K
        echo IiVQWSUiIC1tIHBpcCAtLXZlcnNpb24NCmVjaG8uDQoNCmVjaG8gLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tDQplY2hvICBJbnN0YWxs
        echo ZWQgUGFja2FnZXMNCmVjaG8gLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tDQoiJVBZJSIgLW0gcGlwIGxpc3QNCmVjaG8uDQoNCmVjaG8g
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tDQplY2hvICBEZXBlbmRlbmN5IEhlYWx0aA0KZWNobyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0NCiIlUFklIiAtbSBwaXAgY2hl
        echo Y2sNCmVjaG8uDQoNCmVjaG8gLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tDQplY2hvICBFbnRyeSBQb2ludCBDaGVjaw0KZWNobyAtLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0N
        echo CmlmIC9JICIlRU5UUllfTU9ERSUiPT0iZmlsZSIgKA0KICAgIGlmIGV4aXN0ICIlQVBQX0VOVFJZ
        echo JSIgKA0KICAgICAgICBlY2hvIFtPS10gRW50cnkgZmlsZSBmb3VuZDogIiVBUFBfRU5UUlklIg0K
        echo ICAgICkgZWxzZSAoDQogICAgICAgIGVjaG8gW0ZBSUxdIEVudHJ5IGZpbGUgTk9UIGZvdW5kOiAi
        echo JUFQUF9FTlRSWSUiDQogICAgKQ0KKSBlbHNlICgNCiAgICAiJVBZJSIgLWMgImltcG9ydCBpbXBv
        echo cnRsaWIudXRpbCwgc3lzOyBuYW1lPXInJUFQUF9FTlRSWSUnOyBzcGVjPWltcG9ydGxpYi51dGls
        echo LmZpbmRfc3BlYyhuYW1lKTsgcHJpbnQoKCdbT0tdIE1vZHVsZSBmb3VuZDogJyBpZiBzcGVjIGVs
        echo c2UgJ1tGQUlMXSBNb2R1bGUgTk9UIGZvdW5kOiAnKSArIG5hbWUpOyBzeXMuZXhpdCgwIGlmIHNw
        echo ZWMgZWxzZSAxKSIgMj5udWwNCiAgICBpZiBlcnJvcmxldmVsIDEgZWNobyBbRkFJTF0gTW9kdWxl
        echo IGltcG9ydCB0ZXN0IGZhaWxlZC4NCiAgICBpZiAvSSAiJUVOVFJZX01PREUlIj09InJ1bm5lciIg
        echo ZWNobyBbSU5GT10gUnVubmVyIGFyZ3M6ICIlUlVOTkVSX0FSR1MlIg0KKQ0KZWNoby4NCg0KZWNo
        echo byAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0NCmVjaG8gIFByb2plY3QgRmlsZXMNCmVjaG8gLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tDQppZiBleGlzdCAidXYubG9jayIg
        echo ICAgICAgICAgZWNobyBbT0tdICAgdXYubG9jayBmb3VuZA0KaWYgZXhpc3QgInB5cHJvamVjdC50
        echo b21sIiAgIGVjaG8gW09LXSAgIHB5cHJvamVjdC50b21sIGZvdW5kDQppZiBleGlzdCAicmVxdWly
        echo ZW1lbnRzLnR4dCIgZWNobyBbT0tdICAgcmVxdWlyZW1lbnRzLnR4dCBmb3VuZA0KaWYgbm90IGV4
        echo aXN0ICJyZXF1aXJlbWVudHMudHh0IiBlY2hvIFtXQVJOXSByZXF1aXJlbWVudHMudHh0IG1pc3Np
        echo bmcNCmVjaG8uDQoNCmVjaG8gLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tDQplY2hvICBQeVF0NiBXZWJFbmdpbmUgQ2hlY2sNCmVjaG8g
        echo LS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0t
        echo LS0tDQoiJVBZJSIgLWMgImZyb20gUHlRdDYgaW1wb3J0IFF0Q29yZTsgcHJpbnQoJ1B5UXQ6Jywg
        echo UXRDb3JlLlBZUVRfVkVSU0lPTl9TVFIpOyBwcmludCgnUXQgIDonLCBRdENvcmUuUVRfVkVSU0lP
        echo Tl9TVFIpOyBmcm9tIFB5UXQ2LlF0V2ViRW5naW5lV2lkZ2V0cyBpbXBvcnQgUVdlYkVuZ2luZVZp
        echo ZXc7IHByaW50KCdbT0tdIFdlYkVuZ2luZSBpbXBvcnRlZCBzdWNjZXNzZnVsbHkuJykiIDI+JjEN
        echo CmlmIGVycm9ybGV2ZWwgMSAoDQogICAgZWNobyBbRkFJTF0gUHlRdDYgV2ViRW5naW5lIGNoZWNr
        echo IGZhaWxlZC4NCiAgICBlY2hvICAgICAgICBSdW4gbWFudWFsbHkgZm9yIGZ1bGwgdHJhY2ViYWNr
        echo Og0KICAgIGVjaG8gICAgICAgICIlUFklIiAtYyAiZnJvbSBQeVF0Ni5RdFdlYkVuZ2luZVdpZGdl
        echo dHMgaW1wb3J0IFFXZWJFbmdpbmVWaWV3Ig0KKSBlbHNlICgNCiAgICBlY2hvIFtPS10gUHlRdDYg
        echo V2ViRW5naW5lIGlzIGF2YWlsYWJsZS4NCikNCmVjaG8uDQoNCmVjaG8gPT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQplY2hvICBET0NU
        echo T1IgQ09NUExFVEUNCmVjaG8gPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09DQpwYXVzZQ0KZXhpdCAvYiAwDQo=
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

rem ── test.bat ─────────────────────────────────────────────────
set "OUTFILE=test.bat"
if exist "%OUTFILE%" (
    echo [SKIP] %OUTFILE% already exists
) else (
    set "TMP_B64=%TEMP%\vbg_test_bat.b64"
    (
        echo QGVjaG8gb2ZmDQpzZXRsb2NhbA0KY2QgL2QgIiV+ZHAwIg0KDQpyZW0gPT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09DQpyZW0gIFByb2pl
        echo Y3QgdGVzdCBydW5uZXINCnJlbSAgR2VuZXJhdGVkIGJ5IFZlbnYgQmF0Y2ggVGVtcGxhdGUgR2Vu
        echo ZXJhdG9yIChMZW9uIFByaWVzdCAvIDdoM3YwMWQpIHYzLjQuMA0KcmVtICBHZW5lcmF0ZWQgb246
        echo IDIwMjYtMDctMjAgMDA6NDUNCnJlbQ0KcmVtICBSdW5zIHB5dGVzdCB2aWEgdGhlIHByb2plY3Qt
        echo bG9jYWwgdmVudiBQeXRob24uDQpyZW0NCnJlbSAgVXNhZ2U6DQpyZW0gICAgdGVzdC5iYXQgICAg
        echo ICAgICAgICAgICAgICAgICAgICAocnVuIGFsbCB0ZXN0cykNCnJlbSAgICB0ZXN0LmJhdCB0ZXN0
        echo cy90ZXN0X2NvcmUucHkgICAgIChydW4gYSBzcGVjaWZpYyBmaWxlKQ0KcmVtICAgIHRlc3QuYmF0
        echo IC1rIG1hcHBlciAgICAgICAgICAgICAgKGZpbHRlciBieSBuYW1lKQ0KcmVtICAgIHRlc3QuYmF0
        echo IC12IC0tdGI9c2hvcnQgICAgICAgICAgKHZlcmJvc2Ugd2l0aCBzaG9ydCB0cmFjZWJhY2tzKQ0K
        echo cmVtID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PQ0KDQpzZXQgIlBST0pFQ1RfTkFNRT1hZHBfcHJvIg0Kc2V0ICJWRU5WX0RJUj0udmVu
        echo diINCnNldCAiUFk9JUNEJVwlVkVOVl9ESVIlXFNjcmlwdHNccHl0aG9uLmV4ZSINCg0KaWYgbm90
        echo IGV4aXN0ICIlUFklIiAoDQogICAgZWNobyBbRVJST1JdIExvY2FsIHZlbnYgd2FzIG5vdCBmb3Vu
        echo ZDoNCiAgICBlY2hvICAgICAgICAgIiVQWSUiDQogICAgZWNoby4NCiAgICBwYXVzZQ0KICAgIGV4
        echo aXQgL2IgMQ0KKQ0KDQp0aXRsZSAiJVBST0pFQ1RfTkFNRSUgLSBURVNUIg0KZWNobyA9PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCmVj
        echo aG8gIFRlc3Rpbmc6ICIlUFJPSkVDVF9OQU1FJSINCmVjaG8gIFB5dGhvbiA6ICIlUFklIg0KZWNo
        echo byA9PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT0NCmVjaG8uDQoiJVBZJSIgLW0gcHl0ZXN0IC12ICUqDQpzZXQgIkVYSVRDT0RFPSVFUlJP
        echo UkxFVkVMJSINCg0KZWNoby4NCmVjaG8gPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09DQppZiAiJUVYSVRDT0RFJSI9PSIwIiAoDQogICAg
        echo ZWNobyAgVEVTVFMgUEFTU0VEDQopIGVsc2UgKA0KICAgIGVjaG8gIFRFU1RTIEZBSUxFRCAgXihl
        echo eGl0IGNvZGU6ICVFWElUQ09ERSVeKQ0KKQ0KZWNobyA9PT09PT09PT09PT09PT09PT09PT09PT09
        echo PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0NCnBhdXNlDQpleGl0IC9iICVFWElU
        echo Q09ERSUNCg==
    ) > "!TMP_B64!"
    certutil -decode "!TMP_B64!" "%OUTFILE%" >nul 2>&1
    if exist "!TMP_B64!" del "!TMP_B64!"
    if exist "%OUTFILE%" (
        echo [OK]   %OUTFILE%
    ) else (
        echo [FAIL] %OUTFILE% - certutil decode failed. certutil may be blocked or unavailable.
    )
)

echo.
echo ============================================================
echo  SETUP COMPLETE
echo.
echo  Companion scripts written (existing files were NOT overwritten).
echo  Add them to .gitignore to keep your repo tidy.
echo.
echo  Next steps:
echo    run.bat    - Launch %PROJECT_NAME%
echo    sync.bat   - Reinstall / update dependencies
echo    shell.bat  - Open activated venv shell
echo    doctor.bat - Environment health check
echo    pip.bat    - Project-local pip wrapper
echo    test.bat   - Run pytest suite
echo ============================================================
pause
exit /b 0
